name: base
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python>=3.9.*
  - git
  - pip
  - click
  - pygeoapi
  - pandas
  - geopandas
  - rasterstats
  - xarray
  - dask
  - bottleneck
  - numpy
  - metpy
  - netcdf4
  - cartopy
  - matplotlib
  - folium
  - pygeos
  - jupyterlab
  - babel
  - hvplot
  - esmpy
  - xesmf
  - geoviews
  - rioxarray
  - bottleneck
  - snakemake
  - numba
  - pip:
    - git+https://github.com/rmcd-mscb/xagg.git@nc_prep_fix
    - git+https://github.com/rmcd-mscb/grd2shp_xagg.git@main
    - datetime

